name : PMD

on :
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    permissions:
      contents: read
      security-events: write
      actions: read
    name: Run tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: pmd/pmd-github-action@v2
        id: pmd
        with:
          version: '6.55.0'
          sourcePath: 'src/main/java'
          rulesets: 'rulesets/java/quickstart.xml,ruleset.xml'
      - name: "Upload to code-scanning"
        uses: github/codeql-action/upload-sarif@v3
        with:
         sarif_file: pmd-report.sarif